---
title: "Running Novae foundational model"
author: ""
date: "`r format(Sys.Date(), '%m/%d/%Y')`"
abstract: >
    This package takes an h5ad file with the gene count matrix and spatial coordinates as input, runs Novae, creating the Python environment automatically, and returns an annDataR object with the embeddings and domains (spatial clusters).

output:
  rmarkdown::html_document:
    highlight: pygments
    toc: true
vignette: >
  %\VignetteIndexEntry{Running Novae foundational model}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  %\usepackage[utf8]{inputenc}
---

```{r setup}
library(anndataR)
library(SpatialExperiment)
library(fomo)

spe <- readRDS(
  system.file("extdata", "CosMx1k_MouseBrain1_100tx_100cl.rds", package = "fomo")
)
```

Prepare h5ad file for Novae

```{r h5ad_creation}
adata <- as_AnnData(spe)

# add coordinates to metadata
spatialCoords(spe) |> as.data.frame() -> coords_df
adata$obs$x_coord <- coords_df[, 1]
adata$obs$y_coord <- coords_df[, 2]

# add coordinates as spatial
coords <- as.matrix(spatialCoords(spe))
rownames(coords) <- adata$obs_names
adata$obsm$spatial <- coords
colnames(adata$obsm$spatial) <- c("x_coord", "y_coord")

# write anndata to tempfile 
adata$write_h5ad(
  tp <- tempfile(fileext = ".h5ad"), 
  mode = "w"
)
```

Run Novae

```{r running_novae}
novae_data <- Run_novae(tp, accelerator = "cpu")
dim(novae_data$obsm$novae_latent)
```

Add novae embeddings and annotations to SPE object

```{r add_embed}
reducedDim(spe, "novae_latent") <- novae_data$obsm$novae_latent
spe$domain <- as.character(novae_data$obs$novae_domains_7)
```

Plotting spatial coordinates coloured by Novae's defined clusters (domains)

```{r plot_results}
library(ggspavis)
spe$in_tissue <- 1
spe$x_centroid <- spe$y_centroid <- NULL
plotCoords(spe, annotate = "domain", point_size = 2)
```

```{r sessionInfo}
sessionInfo()
```
